#!/usr/bin/env bash
# Generate .clangd from the Nix dev shell environment.
# Called automatically by `nix develop` via shellHook.
# Run manually after `nix flake update` if you're outside the shell.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# ── compile_commands.json symlink ──────────────────────────────────────────
if [ ! -f "$ROOT/compile_commands.json" ]; then
  if [ -f "$ROOT/build/compile_commands.json" ]; then
    ln -sf build/compile_commands.json "$ROOT/compile_commands.json"
    echo "Symlinked build/compile_commands.json → compile_commands.json"
  fi
fi

# ── Gather include paths ──────────────────────────────────────────────────
ALL_INCLUDES=()

# 1) -isystem paths from NIX_CFLAGS_COMPILE (package headers)
NEXT_IS_ISYSTEM=0
for flag in ${NIX_CFLAGS_COMPILE:-}; do
  if [ "$flag" = "-isystem" ]; then
    NEXT_IS_ISYSTEM=1
  elif [ "$NEXT_IS_ISYSTEM" -eq 1 ]; then
    ALL_INCLUDES+=("$flag")
    NEXT_IS_ISYSTEM=0
  elif [[ "$flag" == -isystem/* ]]; then
    ALL_INCLUDES+=("${flag#-isystem}")
  fi
done

# 2) GCC internal include paths (glibc headers, GCC fixed includes)
#    These are added by the Nix GCC wrapper via -idirafter and don't appear
#    in NIX_CFLAGS_COMPILE — we query GCC directly.
GCC_BIN=$( (grep -om1 '/nix/store/[^"]*-gcc-wrapper[^"]*/bin/gcc' \
           "$ROOT/build/compile_commands.json" 2>/dev/null) || true)
if [ -n "$GCC_BIN" ]; then
  while IFS= read -r line; do
    ALL_INCLUDES+=("$line")
  done < <(env -i PATH="$PATH" "$GCC_BIN" -E -x c - -v < /dev/null 2>&1 \
           | grep "^ /" | grep -v '/cc1\b' | sed 's/^ //')
fi

# ── Deduplicate while preserving order ────────────────────────────────────
declare -A SEEN
UNIQUE=()
for inc in "${ALL_INCLUDES[@]}"; do
  [ -z "$inc" ] && continue
  if [ -z "${SEEN[$inc]-}" ]; then
    UNIQUE+=("$inc")
    SEEN["$inc"]=1
  fi
done

if [ ${#UNIQUE[@]} -eq 0 ]; then
  echo "No include paths found — something is wrong."
  exit 1
fi

# ── Write .clangd ─────────────────────────────────────────────────────────
cat > "$ROOT/.clangd" <<- EOF
# Generated by scripts/gen_clangd.sh — do not edit manually.
# Regenerate: nix develop  (or  ./scripts/gen_clangd.sh)

CompileFlags:
  Add:
EOF

for inc in "${UNIQUE[@]}"; do
  echo "    - \"-isystem$inc\"" >> "$ROOT/.clangd"
done

echo "Generated .clangd with ${#UNIQUE[@]} unique include paths"
echo "  → Nix GCC + package headers mapped for clangd"
